### ISSUE TITLE
Issue running gq.py

### ISSUE THREAD

**Issue by michaelviney** [qiaoguan/Fall-detection#8]
Hi there,

Im receiving this error when Im trying to run gq.py:

Traceback (most recent call last):
  File "gq.py", line 5, in <module>
    import darknet as dn
  File "python/darknet.py", line 40, in <module>
    lib = CDLL("libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libdarknet.so: cannot open shared object file: No such file or directory

When I edit python/darknet.py to absolute path I receive:

Traceback (most recent call last):
  File "gq.py", line 5, in <module>
    import darknet as dn
  File "python/darknet.py", line 39, in <module>
    lib = CDLL("/home/michael/Fall-detection/libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopencv_core.so.2.4: cannot open shared object file: No such file or directory

Please help!!!

**Comment by michaelviney** [comment]
I have version 3.2.0 running. Should I be modifying all references to cv2 to cv3?

**Comment by michaelviney** [comment]
Thank you Ive now got it working! However I received a final error when the fall detection was attempted: 

(Fall detection:23334): Gtk-ERROR **: 23:03:26.280: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)

**Comment by zql1314** [comment]
I alter the relative path for libdarknet.so in python/darknet.py to absolute path，but it do not work.
 File "E:/Fall-detection-master/gq.py", line 5, in <module>
    import darknet as dn
  File "python\darknet.py", line 40, in <module>
    lib = CDLL("E:/Fall-detection-master/libdarknet.so", RTLD_GLOBAL)
  File "D:\python\python2\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 ������Ч�� Win32
Please help

**Comment by JohnWang1998** [comment]
I have the same problem like the aforementioned question raised

**Comment by lightclicks** [comment]
> the first question, If libdarknet.so Error happened, you can alter the relative path for libdarknet.so in python/darknet.py to absolute path.
> For the second question, just check the version of your opencv， cause the api of opencv may have changed, change the code to the api of your version

hi,could please tell me where should i change the code to the api of opencv?
